# Generated by Django 4.2 on 2023-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_customuser_prouser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prouser',
            options={'verbose_name_plural': 'ProUsers'},
        ),
    ]
