# Generated by Django 4.2 on 2023-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_alter_prouser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prouser',
            name='is_creator',
            field=models.BooleanField(default=True),
        ),
    ]
